name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  size-label:
    name: 📏 Medir Tamaño del PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Etiquetar tamaño
        uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "0": "XS",
              "100": "S",
              "300": "M",
              "700": "L",
              "1500": "XL"
            }
